models:
  - type: main
    engine: ryan_local_engine                 # use environment variables, set ryan_vllm_engine as default
    model: Qwen2_BE_0.6B
    parameters:
      model_path: /home/ubuntu/workspace/llm/models/Qwen2_BE_0.6B
      checkpoint_path: ''                                                                                                            # 确保路径正确
      device: cpu             # "cpu" or "cuda"
      # num_gpus: 1  # if use GPU, specific the nums

# streaming : true

custom_data:
  sensitive_words_file: "./resources/sensitive_words.txt"
  profanity_words_file: "./resources/profanity_words.txt"
  level: ${LOG_LEVEL:-DEBUG}      # DEBUG|INFO|WARNING|ERROR|CRITICAL
  disabled: false     # true|false

rails:
  input:
    flows:
      - input rails

  dialog:
    single_call:
      enabled: false
      fallback_to_multiple_calls: true
    user_messages:
      embeddings_only: false
