models:
  - type: main
    engine: ryan_vllm_engine                  # use environment variables, set ryan_vllm_engine as default
    model: Qwen2.5-7B-Instruct
    parameters:
      model_path: /home/ryan_niu/ryan/llm/models/Qwen2.5-7B-Instruct
      checkpoint_path: ''                                                                                                            # 确保路径正确
      device: cuda            # "cpu" or "cuda"
      # num_gpus: 1  # if use GPU, specific the nums

streaming: true
stream_interval: 2  # 可选：控制流式响应间隔

custom_data:
  sensitive_words_file: "./resources/sensitive_words.txt"
  profanity_words_file: "./resources/profanity_words.txt"
  level: ${LOG_LEVEL:-DEBUG}      # DEBUG|INFO|WARNING|ERROR|CRITICAL
  disabled: false     # true|false

rails:
  input:
    flows:
      - input rails

  dialog:
    single_call:
      enabled: false
      fallback_to_multiple_calls: true
    user_messages:
      embeddings_only: false
